.TH "Circle" 3 "Tue Nov 3 2020" "Shapes Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circle \- < \fBCircle\fP inherits from ellipse  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Circle\&.h>\fP
.PP
Inherits \fBEllipse\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCircle\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBCircle\fP (sf::Vector2f middle, float radius, int n)"
.br
.RI "Constructor initialising the position and size as well as resolution\&. "
.ti -1c
.RI "\fB~Circle\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "void \fBmakeCircle\fP ()"
.br
.RI "Function that makes ellipse\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
< \fBCircle\fP inherits from ellipse 
.SH "Member Function Documentation"
.PP 
.SS "void Circle::makeCircle ()"

.PP
Function that makes ellipse\&. < Calculate position for each point around middle
.PP
< Connect last point with first to make full shape

.SH "Author"
.PP 
Generated automatically by Doxygen for Shapes Library from the source code\&.
