.TH "Dot" 3 "Tue Nov 3 2020" "Shapes Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDot\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBDot\fP (float fpX, float fpY)"
.br
.RI "Constructor initialising the position\&. "
.ti -1c
.RI "\fB~Dot\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "void \fBmakeDot\fP ()"
.br
.RI "Function that makes dot\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Dot::Dot ()"

.PP
Default constructor\&. < Sets point-style type how to draw

.SH "Author"
.PP 
Generated automatically by Doxygen for Shapes Library from the source code\&.
