.TH "Ellipse" 3 "Tue Nov 3 2020" "Shapes Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ellipse \- < \fBEllipse\fP inherits from arc  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ellipse\&.h>\fP
.PP
Inherits \fBArc\fP\&.
.PP
Inherited by \fBCircle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEllipse\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBEllipse\fP (sf::Vector2f middle, sf::Vector2f radius, int n)"
.br
.RI "Constructor initialising the position and size as well as resolution\&. "
.ti -1c
.RI "\fB~Ellipse\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "void \fBmakeEllipse\fP ()"
.br
.RI "Function that makes ellipse\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
< \fBEllipse\fP inherits from arc 
.SH "Member Function Documentation"
.PP 
.SS "void Ellipse::makeEllipse ()"

.PP
Function that makes ellipse\&. < Calculate position for each point around middle
.PP
< Connect last point with first to make full shape

.SH "Author"
.PP 
Generated automatically by Doxygen for Shapes Library from the source code\&.
