.TH "Line" 3 "Tue Nov 3 2020" "Shapes Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Line
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLine\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBLine\fP (sf::Vector2f xy1, sf::Vector2f xy2)"
.br
.RI "Constructor initialising the position\&. "
.ti -1c
.RI "\fB~Line\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "void \fBmakeLine\fP ()"
.br
.RI "Function that makes line\&. "
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Shapes Library from the source code\&.
