.TH "Rectangle" 3 "Tue Nov 3 2020" "Shapes Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rectangle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape\fP\&.
.PP
Inherited by \fBSquare\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRectangle\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBRectangle\fP (sf::Vector2f middle, float fWidthTemp, float fHeightTemp)"
.br
.RI "Constructor initialising the position and size\&. "
.ti -1c
.RI "\fB~Rectangle\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "void \fBmakeRectangle\fP ()"
.br
.RI "Function that makes rectangle\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBfWidth\fP"
.br
.ti -1c
.RI "float \fBfHeight\fP"
.br
.RI "Variable that stores width and height of rectangle\&. "
.ti -1c
.RI "sf::Vector2f \fBcentre\fP"
.br
.RI "Variable that stores centre position\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Rectangle::makeRectangle ()"

.PP
Function that makes rectangle\&. < Connect last point with first to make full shape

.SH "Author"
.PP 
Generated automatically by Doxygen for Shapes Library from the source code\&.
