.TH "Square" 3 "Tue Nov 3 2020" "Shapes Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Square \- < \fBSquare\fP inherits from rectangle  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Square\&.h>\fP
.PP
Inherits \fBRectangle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSquare\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBSquare\fP (sf::Vector2f middle, float size)"
.br
.RI "Constructor initialising the position and size\&. "
.ti -1c
.RI "\fB~Square\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "void \fBmakeSquare\fP ()"
.br
.RI "Function that makes square\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
< \fBSquare\fP inherits from rectangle 
.SH "Member Function Documentation"
.PP 
.SS "void Square::makeSquare ()"

.PP
Function that makes square\&. < Connect last point with first to make full shape

.SH "Author"
.PP 
Generated automatically by Doxygen for Shapes Library from the source code\&.
