.TH "Triangle" 3 "Tue Nov 3 2020" "Shapes Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Triangle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriangle\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBTriangle\fP (sf::Vector2f xy1, sf::Vector2f xy2, sf::Vector2f xy3)"
.br
.RI "Constructor initialising the position\&. "
.ti -1c
.RI "\fB~Triangle\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "void \fBmakeTriangle\fP ()"
.br
.RI "Function that makes triangle\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void Triangle::makeTriangle ()"

.PP
Function that makes triangle\&. < Connect last point with first to make full shape

.SH "Author"
.PP 
Generated automatically by Doxygen for Shapes Library from the source code\&.
